[package]
name = "tuigreet"
version = "0.4.0"
authors = ["Antoine POPINEAU <antoine.popineau@appscho.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
getopts = "0.2.21"
greetd_ipc = { version = "0.6.0", features = ["sync-codec"] }
termion = "1.5.6"
tui = "0.15.0"
nix = "0.21.0"
textwrap = "0.14.0"
chrono = "0.4.19"
zeroize = "1.3.0"
rust-ini = "0.17.0"

[profile.release]
lto = true
